### ISSUE TITLE
add email confiuration

### ISSUE THREAD

**Issue by ghaseminya** [sdksdk0/BookStore#1]
Hi @sdksdk0
I run your project on Apache Tomcat,
Some changes needed!!!
db.sql have some error!:
"photo" in customers table must be change to "phone".
lines 114 to 123 must move after line 127.

I think if you add a config file for set email username and password your project is a good sample for shopping.
Thanks

**Comment by sdksdk0** [comment]
Hi @ghaseminya 
Very good advice, I will further modify, thank you very much for your support. 
Thank you !

**Comment by ChristianLeonhard** [comment]
请问一下大牛，您的项目我在tomcat上运行后，主页地址是多少？几个index都提示404

**Comment by sdksdk0** [comment]
@ChristianLeonhard 试一下login.jsp页面
